services:
    server:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './api:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'
        networks:
            - todos

    php-fpm:
        build: ./docker/php-fpm
        working_dir: /application
        volumes:
            - './api:/application'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/cli/conf.d/99-overrides.ini'
        networks:
            - todos

    mysql:
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - './api:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=todos
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        ports:
            - '3306:3306'
        networks:
            - todos

networks:
    todos:
        driver: bridge

volumes:
    mysql:
        driver: local